# Generated by Django 4.2.6 on 2023-10-25 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_image_options_alter_image_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="MainImage",
        ),
    ]
