# Generated by Django 4.2.6 on 2023-10-26 05:11

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_rename_image_mainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Текст",
                validators=[
                    catalog.validators.MustContainValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
